seed: 42
num_epochs: 40
accum_steps: 16
checkpoint_dir: "checkpoints"
checkpoint_freq: 10
dropout_rate: 0.2
optimizer:
  lr: 5e-4
  betas: [0.9, 0.999]
  weight_decay: 1e-4
scheduler:
  warmup_epochs: 5
early_stopping: null
data:
  data_dir: "data"
  train_bs: 32
  test_bs: 32
  im_size: [32, 32]
